import "@radix-ui/themes/styles.css";
import "easymde/dist/easymde.min.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import { ReactNode } from "react";
import { QueryProvider } from "@/providers/query-provider";
import AuthProvider from "@/providers/auth-provider";
import { NavBar } from "@/components/nav-bar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>
            <Theme accentColor="violet" radius="large" scaling="110%">
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
              <ThemePanel />
            </Theme>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
